In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('unigram_freq.csv')

df.head(5)

  word        count
0  the  23135851162
1   of  13151942776
2  and  12997637966
3   to  12136980858
4    a   9081174698

In [4]:
df_5 = df[df['word'].str.len() == 5]

df_5.info()

<class 'pandas.DataFrame'>
Index: 39933 entries, 35 to 333332
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   word    39933 non-null  str
 1   count   39933 non-null  int64
dtypes: int64(1), str(1)
memory usage: 935.9 KB

In [5]:
df_5

         word       count
35      about  1226734006
45      other   978481319
56      which   810514085
57      their   782849411
62      there   701170205
...       ...         ...
333307  goovo       12711
333308  goova       12711
333320  goolh       12711
333328  gooek       12711
333332  golgw       12711

[39933 rows x 2 columns]

In [6]:
#reindex the dataframe to have a new index starting from 0
df_5 = df_5.reset_index(drop=True)

df_5

        word       count
0      about  1226734006
1      other   978481319
2      which   810514085
3      their   782849411
4      there   701170205
...      ...         ...
39928  goovo       12711
39929  goova       12711
39930  goolh       12711
39931  gooek       12711
39932  golgw       12711

[39933 rows x 2 columns]

In [7]:
# add a new column for points based on rank/index order
# wan to noramlize based on the max rank, so that the highest rank gets 1 point and the lowest rank gets 0 points based on frequency in the dataset
df_5['points'] = (df_5.index.max() - df_5.index) / df_5.index.max() 
df_5

        word       count    points
0      about  1226734006  1.000000
1      other   978481319  0.999975
2      which   810514085  0.999950
3      their   782849411  0.999925
4      there   701170205  0.999900
...      ...         ...       ...
39928  goovo       12711  0.000100
39929  goova       12711  0.000075
39930  goolh       12711  0.000050
39931  gooek       12711  0.000025
39932  golgw       12711  0.000000

[39933 rows x 3 columns]

In [8]:
df_5.to_csv('unigram_freq_5.csv', index=True)

In [9]:
wordle = pd.read_csv('wordle.csv')
wordle = wordle[["word", "occurrence"]]
wordle

        word    occurrence
0      aahed  1.850950e-09
1      aalii  6.224471e-10
2      aargh  2.158188e-10
3      aarti  7.668332e-10
4      abaca  6.320646e-08
...      ...           ...
12967  zuzim  4.259832e-09
12968  zygal  7.210628e-10
12969  zygon  1.448293e-09
12970  zymes  1.359240e-08
12971  zymic  4.625087e-10

[12972 rows x 2 columns]

In [10]:
wordle_referenced = pd.merge(df_5, wordle, how='left', left_on='word', right_on='word')
wordle_referenced = wordle_referenced.dropna()

wordle_referenced

        word       count    points    occurrence
0      about  1226734006  1.000000  1.053332e-03
1      other   978481319  0.999975  1.333864e-03
2      which   810514085  0.999950  2.430560e-03
3      their   782849411  0.999925  1.664544e-03
4      there   701170205  0.999900  1.020133e-03
...      ...         ...       ...           ...
39344  sadis       12774  0.014725  2.546107e-09
39502  maist       12738  0.010768  4.082824e-08
39516  hully       12736  0.010418  2.859694e-09
39660  intil       12721  0.006812  2.039226e-08
39739  toits       12716  0.004833  2.853070e-08

[8092 rows x 4 columns]

In [17]:
wordle_referenced.to_csv('wordle_referenced.csv', index=True)
wordle_referenced = wordle_referenced.drop(columns=['occurrence'])
wordle_referenced

        word   count    points
14150  aargh   71592  0.645648
15298  aarti   63273  0.616899
13237  abaca   79841  0.668511
6535   aback  272920  0.836347
31424  abaft   19188  0.213062
...      ...     ...       ...
15986  zupan   58811  0.599669
21382  zuppa   36160  0.464540
35506  zygon   15300  0.110838
27725  zymes   24137  0.305695
23853  zymic   30459  0.402660

[8092 rows x 3 columns]

In [16]:
# Alphabetical order of the words in the wordle_referenced dataframe
wordle_referenced = wordle_referenced.sort_values(by='word')
wordle_referenced.to_csv('wordle_referenced.csv', index=True)